name: Docker Image CI

on:
  push:
    branches: master

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: m9ffk4/kscript:$(git rev-parse --short "$GITHUB_SHA")-${GITHUB_REF##*/}
